### ISSUE TITLE
Issue on mobile: wrong space on l-grid and l-mobile-one-whole

### ISSUE THREAD

**Issue by corinneroelli** [meodai/bonescss#2]
![screen shot 2015-02-10 at 13 42 22](https://cloud.githubusercontent.com/assets/6328642/6127451/51a56a18-b12b-11e4-8c97-f0a437b79194.png)

Added following code to my css and it solves the issue. But I think it should be fixed in the bonescss.

	@include breakpoint(mobile) {
		.l-grid {
      		margin-right: 0;
  		}
   		.l-grid .l-grid-cell.l-mobile-one-whole {
   	  		padding-right: 0;
   		}
	}

**Comment by meodai** [comment]
The grid is supposed to have a negative margin-right. Make sure you don't
reset that anywhere.

**Comment by corinneroelli** [comment]
I don't reset the margin: 
![screen shot 2015-02-11 at 11 46 16](https://cloud.githubusercontent.com/assets/6328642/6145600/d28c771c-b1e3-11e4-9d03-c08e4d59143c.png)
![screen shot 2015-02-11 at 11 46 30](https://cloud.githubusercontent.com/assets/6328642/6145601/d28ead2a-b1e3-11e4-8c6f-56f826920aae.png)
I think the problem is, when the margin-right: -30px and padding-right: 30px is bigger than the padding-right on the l-site-width. It happens only on mobile, then it allows you to scroll.

Ahh.. I'm defining the gutter like this:

$s-gutter: 20px !default;
$s-gutter-medium : $s-gutter * 1.5;

@include sensibleGrid(
  $gutter: $s-gutter-medium
);
And then it doesn't allow me to set the padding right and left on l-site-width to 20px. If I define it to 30px as well – your grid works perfect.

But it would be great to have a smaller gutter on mobile than on desktop.

**Comment by meodai** [comment]
Ah I understand you Problem now. Of course that happens because by default
the grid works with a negative margin on its container. Now you have
3 options: you can set its parent to overflow hidden, you could use the
option 'modern' to use flexbox or you can use the hack you have posted.
Hope that helps

**Comment by corinneroelli** [comment]
Cool, thanks for helping! Yesterday I also tried this:

	@include breakpoint(not-tablet) {
  		@include sensibleGrid(
    		$gutter: $s-gutter-medium
  		);
	}

	@include breakpoint(tablet) {
	  @include sensibleGrid(
	    $gutter: $s-gutter
	  );
	}
But it's really ugly.	
Now I decided for the solution to set its parent to overflow hidden. It's the easiest one. Thanks!
