### ISSUE TITLE
Bug: horizontal-list spacing witih inline-block elements

### ISSUE THREAD

**Issue by lucalanca** [meodai/bonescss#6]
@meodai  Should we add the font-size: 0 trick to this? https://github.com/meodai/bonescss/blob/master/_2.layout.scss#L39

**Comment by meodai** [comment]
@lucalanca not sure. Its annoying due to its side-effects, (reseting EM for example): 
https://css-tricks.com/fighting-the-space-between-inline-block-elements/

**Comment by meodai** [comment]
@lucalanca do you still ahve an issue with this?

**Comment by meodai** [comment]
@lucalanca just make use of the inline-block-fix mixin.
